
var animalDict: [String: String] = [
        "Ant" : "Ant has six legs",
        "Bear" : "Bears loves honey",
        "Cat" : "Cats like to pounce",
        "Dog" : "Dogs are loyal animals",
        "Duck" : "Ducks can swim",
        "Elephant" : "Elephants have a long trunk",
        "Eagle" : "Eagles are skilled hunters",
        "Frog" : "Frogs are amphibians.",
        "Goat" : "Goat is a domesticated animal",
        "Goose" : "Goose can lay eggs",
        "Horse" : "Horses sleep standing up",
        "Iguana" : "Iguanas are large lizards",
        "Jellyfish" : "Jellyfish shines in dark",
        "Kangaroo" : "Kangaroo have fur coats",
        "Lion" : "lion is king of jungle",
        "Lamb" : "Lambs drink milk",
        "Monkey" : "Monkeys are intelligent animals",
        "Mouse" : "Mouse loves cheese",
        "Octopus" : "Octopus have eight arms",
        "Owl" : "Owls fly at night ",
        "Panda" : "Panda loves to eat Bamboo",
    //    "Pig" : "pig pig2",
        "Rabbit" : "Rabbits eat veggies",
        "Raccoon" : "Raccoons are nocturnal/Raccoons are opportunistic eaters",
        "Snake" : "Snake is a reptile",
        "Tiger" : "Tiger plays in the water",
        "Turtle" : "Turtles live up to 100 years",
        "Unicorn" : "Unicorn is a mythical animal",
        "Vulture" : "Vultures are large bird",
        "Whale" : "Whales are the largest animals",
    //    "Xenops" : "Xenops",
    //    "Yak" : "yak yak3",
        "Zebra" : "Zebras pattern are unique"
]

var imageAnimalDict: [String: [String]] = [
        "Ant" : ["ant", "six_ants"],
        "Bear" : ["bear"],
        "Cat" : ["cat", "three_cats"],
        "Dog" : ["dog"],
        "Duck" : ["duck", "five_duck"],
        "Elephant" : ["elephant", "elephant2", "three_elephant", "four_elephant"],
        "Eagle" : ["eagle"],
        "Frog" : ["frog", "frog2", "frog3"],
        "Goat" : ["goat"],
        "Goose" : ["goose"],
        "Horse" : ["horse"],
        "Iguana" : ["iguana", "iguana2"],
        "Jellyfish" : ["jelly_fish"],
        "Kangaroo" : ["kangaroo"],
        "Lion" : ["lion", "lion2"],
        "Lamb" : ["lamb"],
        "Monkey" : ["monkey", "monkey2", "monkey3"],
        "Mouse" : ["Mouse", "mouse2", "Mouse3", "mouse4"],
        "Octopus" : ["octopus", "octopus2", "eight_octopus"],
        "Owl" : ["owl", "owl2", "owl3", "four_owl"],
        "Panda" : ["panda", "panda2"],
        "Pig" : ["pig", "pig2"],
        "Rabbit" : ["rabbit", "rabbit2"],
        "Raccoon" : ["raccoon", "raccoon2"],
        "Snake" : ["snake"],
        "Tiger" : ["tiger", "tiger2", "tiger3", "tiger4", "tiger5"],
        "Turtle" : ["turtle", "turtle2", "turtle3"],
        "Unicorn" : ["unicorn", "unicorn2", "unicorn3", "unicorn4", "unicorn5"],
        "Vulture" : ["vulture", "vulture2"],
        "Whale" : ["whale", "whale2", "whale3"],
        "Xenops" : ["Xenops"],
        "Yak" : ["yak", "yak2", "yak3"],
        "Zebra" : ["zebra", "zebra2", "three_zebra"]
]